In [1]:
from filtros import *
from functions import *
from fit_voc import *
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
def log_a(a,x):
    y = np.log(x)/np.log(a)
    return y

In [30]:
SR =         ["100-0    ",
              "100-25   ",
              "75-0     ",
              "100-50   ",
              "75-25    ",
              "50-0     ",
              "100-75   ",
              "75-50    ",
              "62.5-37.5",
              "50-25    ",
              "25-0     ",]

percentage =  [1.00000,
            0.78750,
            1.12525,
            0.43750,
            0.68750,
            1.03125,
            0.40625,
            0.29700,
            0.28125,
            0.62500,
            1.00000]

base_data = list(zip(SR,percentage))
base_headers = ["SR","Percent"]
base_table = pd.DataFrame(base_data,columns=base_headers)

### Simulamos el caso de una celda nueva

In [31]:
# Datos del Datasheet
new_EOL = 0.7
new_cycles = 500
new_SR = 0.8

# Obtenemos los ciclos equivalentes de la nueva celda
new_cycles_eq = 500*new_SR
# Calculamos el eta y los ciclos para el EOL de la tabla proporcional
new_eta_0 = new_EOL**(1/new_cycles_eq)
# Obtenemos los ciclos equivalentes para el EOL original de la tabla
new_cycles_eq_08 = 1/log_a(0.8,new_eta_0)

In [32]:
EQ_cycles = []
for percentage in base_table.Percent.values:
    eq_cycle_k = percentage*new_cycles_eq_08
    # eq_cycle_k = percentage*500
    EQ_cycles.append(eq_cycle_k)
base_table["EQ_cycles"] = EQ_cycles

base_table

           SR  Percent   EQ_cycles
0   100-0      1.00000  250.248642
1   100-25     0.78750  197.070806
2   75-0       1.12525  281.592285
3   100-50     0.43750  109.483781
4   75-25      0.68750  172.045942
5   50-0       1.03125  258.068913
6   100-75     0.40625  101.663511
7   75-50      0.29700   74.323847
8   62.5-37.5  0.28125   70.382431
9   50-25      0.62500  156.405402
10  25-0       1.00000  250.248642

In [34]:
# agregamos los subciclos que induce cada factor
cycles_0 = 500
EOL_0 = 0.7
eta_0 = EOL_0**(1/cycles_0)
EQ_cycles = []

for percentage in base_table.Percent.values:
    eq_cycle_k = percentage*cycles_0
    EQ_cycles.append(eq_cycle_k)
base_table["EQ_cycles_validacion"] = EQ_cycles

base_table

           SR  Percent   EQ_cycles  EQ_cycles_validacion
0   100-0      1.00000  250.248642               500.000
1   100-25     0.78750  197.070806               393.750
2   75-0       1.12525  281.592285               562.625
3   100-50     0.43750  109.483781               218.750
4   75-25      0.68750  172.045942               343.750
5   50-0       1.03125  258.068913               515.625
6   100-75     0.40625  101.663511               203.125
7   75-50      0.29700   74.323847               148.500
8   62.5-37.5  0.28125   70.382431               140.625
9   50-25      0.62500  156.405402               312.500
10  25-0       1.00000  250.248642               500.000

### Ahora calculamos los valorea de eta

In [35]:
eta_values = []
for cycle in base_table.EQ_cycles_validacion.values:
    eta_k = 0.7**(1/cycle)
    eta_values.append(eta_k)
base_table["Eta_EQ_cycles_validacion"] = eta_values

eta_values = []
for cycle in base_table.EQ_cycles.values:
    eta_k = 0.8**(1/cycle)
    eta_values.append(eta_k)
base_table["Eta_EQ_cycles"] = eta_values

base_table

,SR,Percent,EQ_cycles,EQ_cycles_validacion,Eta_EQ_cycles_validacion,Eta_EQ_cycles
0,100-0,1.00000,250.248642,500.000,0.999287,0.999109
1,100-25,0.78750,197.070806,393.750,0.999095,0.998868
2,75-0,1.12525,281.592285,562.625,0.999366,0.999208
3,100-50,0.43750,109.483781,218.750,0.998371,0.997964
4,75-25,0.68750,172.045942,343.750,0.998963,0.998704
5,50-0,1.03125,258.068913,515.625,0.999309,0.999136
6,100-75,0.40625,101.663511,203.125,0.998246,0.997807
7,75-50,0.29700,74.323847,148.500,0.997601,0.997002
8,62.5-37.5,0.28125,70.382431,140.625,0.997467,0.996835
9,50-25,0.62500,156.405402,312.500,0.998859,0.998574
10,25-0,1.00000,250.248642,500.000,0.999287,0.999109